; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = firebeetle32
; PlatformioIO core version 6.1.11
; Platform Espressif 32 version 6.4.0 --> framework-arduinoespressif32 version 2.0.11
; platformio project init --ide vscode

[common]
; DEBUG LEVEL: For production run set to 0, otherwise device will leak RAM while running!
; 0=None, 1=Error, 2=Warn, 3=Info, 4=Debug, 5=Verbose
debug_level = 0

[env:firebeetle32]
platform = espressif32
board = firebeetle32
framework = arduino
lib_ldf_mode = deep+
monitor_speed = 115200
upload_protocol = espota
upload_port = 192.168.20.1
upload_flags =
    --auth=FlyballETS.1234
;    --host_ip=192.168.20.2

board_build.partitions = partitions_custom.csv

lib_deps =
  https://github.com/simonttp78/AsyncTCP @ ^2.0.0
  https://github.com/simonttp78/ESPAsyncWebServer @ ^2.0.0
  bblanchon/ArduinoJson @ ^7.2.0
  https://github.com/thingSoC/embedis @ ^1.2.0
  rweather/Crypto @ ^0.4.0
  JChristensen/Timezone @ ^1.2.4
  arduino-libraries/LiquidCrystal @ ^1.0.7
  mathertel/LiquidCrystal_PCF8574 @^2.2.0

build_flags =
  -I src/modules/
  '-D CORE_DEBUG_LEVEL=${common.debug_level}'